### PR TITLE
fix #103

### LINKED ISSUE #103: error occurs in v0.10
v0.9-release
```
❯ docker run -it --rm -e AUTHORIZER_ZOOKEEPER_CONNECT="..." -e KSM_EXTRACT=true conduktor/kafka-security-manager:v0.9-release

...return acl data. no error :) 
```

v0.10.2-release
```
❯ docker run -it --rm -e AUTHORIZER_ZOOKEEPER_CONNECT="..." -e KSM_EXTRACT=true conduktor/kafka-security-manager:v0.10.2-release

Exception in thread "main" com.typesafe.config.ConfigException$WrongType: application.conf @ jar:file:/opt/docker/lib/com.github.conduktor.ksm.kafka-security-manager-0.10.jar!/application.conf: 9: extract has type OBJECT rather than BOOLEAN
        at com.typesafe.config.impl.SimpleConfig.findKeyOrNull(SimpleConfig.java:163)
        at com.typesafe.config.impl.SimpleConfig.findOrNull(SimpleConfig.java:174)
        at com.typesafe.config.impl.SimpleConfig.find(SimpleConfig.java:188)
        at com.typesafe.config.impl.SimpleConfig.find(SimpleConfig.java:193)
        at com.typesafe.config.impl.SimpleConfig.getBoolean(SimpleConfig.java:218)
        at com.github.conduktor.ksm.AppConfig$KSM$.<init>(AppConfig.scala:62)
        at com.github.conduktor.ksm.AppConfig.KSM$lzycompute$1(AppConfig.scala:58)
        at com.github.conduktor.ksm.AppConfig.KSM(AppConfig.scala:58)
        at com.github.conduktor.ksm.KafkaSecurityManager$.delayedEndpoint$com$github$conduktor$ksm$KafkaSecurityManager$1(KafkaSecurityManager.scala:22)
        at com.github.conduktor.ksm.KafkaSecurityManager$delayedInit$body.apply(KafkaSecurityManager.scala:10)
        at scala.Function0.apply$mcV$sp(Function0.scala:39)
        at scala.Function0.apply$mcV$sp$(Function0.scala:39)
        at scala.runtime.AbstractFunction0.apply$mcV$sp(AbstractFunction0.scala:17)
        at scala.App.$anonfun$main$1$adapted(App.scala:80)
        at scala.collection.immutable.List.foreach(List.scala:392)
        at scala.App.main(App.scala:80)
        at scala.App.main$(App.scala:78)
        at com.github.conduktor.ksm.KafkaSecurityManager$.main(KafkaSecurityManager.scala:10)
        at com.github.conduktor.ksm.KafkaSecurityManager.main(KafkaSecurityManager.scala)
```

latest
```
❯ docker run -it --rm -e AUTHORIZER_ZOOKEEPER_CONNECT="..." -e KSM_EXTRACT=true conduktor/kafka-security-manager:latest
Exception in thread "main" com.typesafe.config.ConfigException$WrongType: application.conf @ jar:file:/opt/docker/lib/com.github.conduktor.ksm.kafka-security-manager-0.11.0-SNAPSHOT.jar!/application.conf: 9: extract has type OBJECT rather than BOOLEAN
        at com.typesafe.config.impl.SimpleConfig.findKeyOrNull(SimpleConfig.java:163)
        at com.typesafe.config.impl.SimpleConfig.findOrNull(SimpleConfig.java:174)
        at com.typesafe.config.impl.SimpleConfig.find(SimpleConfig.java:188)
        at com.typesafe.config.impl.SimpleConfig.find(SimpleConfig.java:193)
        at com.typesafe.config.impl.SimpleConfig.getBoolean(SimpleConfig.java:218)
        at com.github.conduktor.ksm.AppConfig$KSM$.<init>(AppConfig.scala:62)
        at com.github.conduktor.ksm.AppConfig.KSM$lzycompute$1(AppConfig.scala:58)
        at com.github.conduktor.ksm.AppConfig.KSM(AppConfig.scala:58)
        at com.github.conduktor.ksm.KafkaSecurityManager$.delayedEndpoint$com$github$conduktor$ksm$KafkaSecurityManager$1(KafkaSecurityManager.scala:22)
        at com.github.conduktor.ksm.KafkaSecurityManager$delayedInit$body.apply(KafkaSecurityManager.scala:10)
        at scala.Function0.apply$mcV$sp(Function0.scala:39)
        at scala.Function0.apply$mcV$sp$(Function0.scala:39)
        at scala.runtime.AbstractFunction0.apply$mcV$sp(AbstractFunction0.scala:17)
        at scala.App.$anonfun$main$1$adapted(App.scala:80)
        at scala.collection.immutable.List.foreach(List.scala:392)
        at scala.App.main(App.scala:80)
        at scala.App.main$(App.scala:78)
        at com.github.conduktor.ksm.KafkaSecurityManager$.main(KafkaSecurityManager.scala:10)
        at com.github.conduktor.ksm.KafkaSecurityManager.main(KafkaSecurityManager.scala)

```

### PR DESCRIPTION
**Pull request by simplesteph**

### CODE REVIEW

**Comment by simplesteph** [comment]
@ntrp FYI - I implemented something quick on my end

**Comment by eroznik** [comment]
any known/planned release with the fix?

**Comment by simplesteph** [comment]
I'm on it right now: https://github.com/conduktor/kafka-security-manager/actions/runs/892252296

**Comment by ntrp** [comment]
@simplesteph ok thank you very much, I was supposed to come back from vacation last week but my wife derailed everything to go to the sea so I am working remotely and have no extra time right now ^^'. When I find some time will try to add an integration test to avoid this problems in the future.

**Pull request merged**
