### PR TITLE
#103 fix config definition

### PR DESCRIPTION
**Pull request by ntrp**
I am not sure if this fix is acceptable but I tried it and seed to work fine without sideffects. One think I am not sure about is if this is a breaking change for the external config file. If it's not wanted let me know and we can think about another solution.

### CODE REVIEW

**Comment by simplesteph** [comment]
AHHHH I know..

When you added a setting `extract.format`, this created an 

`extract {
  format
}`

which is an OBJECT, and we also define it as `extract = false` before, so there's an overwrite and conflict....

You would need to renamed extract.format to something that doesn't start with `extract.` in order not to conflict the namespace... I'm not sure if we can do 

extract {
    enable = false
    format = csv
} 

while maintaining backward compatibility on the environment variable and config name... 
I'm not a fan of breaking backward compatibility TBH

**Comment by ntrp** [comment]
Well I already did that, just instead I set extract.enable instatead of wraping in an object but the outcome is the same. 
I am also not a fan of breaking backward compatibility but I also would like to avoid hacky solutions not to break backward compatibility, it's still 0.x as you mentioned in the readme :P. 
By the way this would break it only for people that use an external conf file and no environment varibales.

I could also change the format variable name to `extract_format` in case.

**Comment by simplesteph** [comment]
extracting is a manual process anyway, I agree, so probably fine using this. 
Can you please add something for usability:
- if the user specifies the "extract" environment variable or the "extract" config (on its own), then stop the application and show a nice error message saying to migrate to the `extract.enable` config ?
- use `{}` for your setting

Thanks!

**Comment by ntrp** [comment]
Hi I am currently abroad so I have limited time, will try to find some time in the next days. Should be able to do the changes on Thursday I think, will also try to add a integration test to avoid this problem in the future.

**Comment by simplesteph** [comment]
great, then after the fix we'll release 1.0

**Comment by ntrp** [comment]
I actually wanted to integrate directory support soon, I openend already a draft. Should we wait for that one since it's a major feature?

**Comment by simplesteph** [comment]
okay, we can release 0.11 in the meantime

**Comment by simplesteph** [comment]
to be clear, I need this fix to be merged into 0.11, then we release 0.11, then we work on your multi source feature, and we'll release 1.0 :)

**Comment by ntrp** [comment]
Hi, the multi source feature plans on bringing no breaking change, the
system will still support single file sources.

Best regards,
Ivan Gregurić Ortolan

**Comment by simplesteph** [comment]
closing in favor of https://github.com/conduktor/kafka-security-manager/pull/107

**Pull request closed without merging**
